### ISSUE TITLE
error when running createStakepool.sh

### ISSUE THREAD

**Issue by Mercurial** [Chris-Graffagnino/Jormungandr-for-Newbs#11]
Hi, first of all I really appreciate this repository,

but I followed the instructions and I get this error: 

error: Invalid value for '--account-spending-counter <account-spending-counter>': cannot parse integer from empty string when I run the createstakepool script

for example

```
~/files/createStakePool.sh 7777 10 5/100 $(cat ~/files/receiver_secret.key)
```

i get this

```
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:7777/api/v0/account/370ea3477c301cd24f15de5656d04bbc2210157ff8c5f91cda716d480f51f076: Client Error: 404 Not Found
 ##1. Create the offline transaction file
 ##2. Add the Account to the transaction
 ##3. Add the certificate to the transaction
 ##4. Finalize the transaction
 ##5. Make the witness
error: Invalid value for '--account-spending-counter <account-spending-counter>': cannot parse integer from empty string
 ##5. Retrieve your stake pool id (NodeId)
```

**Comment by Mercurial** [comment]
@Chris-Graffagnino

**Comment by Chris-Graffagnino** [comment]
Hi Clark, sorry for the delay... I usually see that answer if the account has a zero balance. You will need 500,300,000 lovelaces to register your stakepool on the blockchain.

**Comment by Mercurial** [comment]
Yes, Thanks maybe I can submit a pull request to display a nice error message for this
